### PR TITLE
Borrow some features from the bazel java_binary wrapper

### PR DESCRIPTION
**Pull request by benley**
* Make --jvm_flag and --jvm_flags work
* Keep $JVM_FLAGS if it is set
* Don't break if $classpath gets ridiculously huge

This makes it possible to do things like set `-Dhttp.proxyHost=foo -Dhttp.proxyPort=1234` for the dev appserver.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pmbethe09** [comment]
seems fine to me, kchodorow can you review this?

**Comment by benley** [comment]
Any chance of getting this merged at some point?

**Comment by pmbethe09** [comment]
LGTM, I can take this.
Can you rebase your PR as it has a merge conflict now

**Comment by kchodorow** [comment]
Sorry, I didn't notice this come in!  LGTM, too.

**Comment by benley** [comment]
Sure thing, I'll get the merge conflicts fixed.

**Comment by benley** [comment]
Done - ready for another look.

**Comment by kchodorow** [comment]
Thanks!

**Pull request merged**
